name: static-frontend
type: php:8.1 # This is for our 404 handler

web: # @see https://docs.platform.sh/create-apps/web/php-basic.html#define-a-front-controller
  locations:
    '/':
      root: 'public'
      index:
        - 'index.html'
      passthru: '/404-handler.php'
